### ISSUE TITLE
What's the relation between this repo and the repo LatticeWordSegmentation?

### ISSUE THREAD

**Issue by x-ji** [fgnt/nhpylm#1]
Hi, I'm searching for implementations related to the Teh 2006 paper and Mochihashi 2009 paper, and found this repo, which seems really promising. However I'm a kind of lost as to the relation between this repo and the repo at https://github.com/fgnt/LatticeWordSegmentation. I see that they both seem to have the same core C++ implementations of the nested hierarchical Pitman-Yor language model. So is it the case that this repo emphasizes Python binding while in that repo everything is done in C++? Are there any other differences regarding the intended use cases and functionalities? I want to edit and apply the model on word segmentation, as described in Mochihashi 2009. Thanks.

**Comment by OliverWalter** [comment]
Hi Ji,

Both, the python version and the C++ use the same implementation of the
NHPYLM.

The python version only provides bindings to train the language model on a
segmented training corpus and apply the language to since test sentence
(either characters or words or a mixture of both). It also contains since
demo code.

The C++ code serves an extended purpose. It implements the unsupervised
segmentation of (partially) unsegmented data according to Mochihashi and
our extensions (see papers by Heymann and Walter).

You could use the Python bindings as well, but you would have to
reimplement the iterations and parsing of results.


   Oliver

**Comment by x-ji** [comment]
Thanks for the clarification!
